export type RootStackParamList = {
  StartingScreen: undefined;
  IntroduceScreen: undefined;
  Introduce1Screen: undefined;
  Introduce2Screen: undefined;
  Introduce3Screen: undefined;
  Introduce4Screen: undefined;
  LoginScreen: undefined;
  SigninScreen: undefined;
  AuthStackNavigator: undefined;
  HomeScreen: undefined;
  NotificationScreen: undefined;
  ProfileScreen: undefined;
  EditProfileScreen: undefined;
  SettingsScreen: undefined;
  NotificationSettingsScreen: undefined;
  SupportCenterScreen: undefined;
  LanguageScreen: undefined;
  RecipeDetailScreen: undefined;
};